[tool.black]
line-length = 100
target-version = ["py312"]

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["agents"]

[tool.mypy]
python_version = "3.12"
strict = true
exclude = ["agents/applicant_evaluator/app/tests"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203","W503"]
